### ISSUE TITLE
看过的推理小说 - 寒光亭下水如天

### ISSUE THREAD

**Issue by IamCatkin** [IamCatkin/myblogcomments#15]
https://blog.catkin.moe/2019/07/04/%E7%9C%8B%E8%BF%87%E7%9A%84%E6%8E%A8%E7%90%86%E5%B0%8F%E8%AF%B4/ 

 看了这么多推理小说，优秀的作品不少，滥竽充数的也很多，因此在这里回顾一下能给我留下印象的推理小说，以作家为单位来推荐。

**Comment by kotori-y** [comment]
今天晚上，要看到你的日记！🙂
