### ISSUE TITLE
推理小说记录 - 寒光亭下水如天

### ISSUE THREAD

**Issue by IamCatkin** [IamCatkin/myblogcomments#19]
https://blog.catkin.moe/2019/09/05/%E6%8E%A8%E7%90%86%E5%B0%8F%E8%AF%B4%E8%AE%B0%E5%BD%95/ 

 谨以此文记录看过的推理小说。

**Comment by yukgan** [comment]
wsnb！俺这种文盲一本都没看过

**Comment by IamCatkin** [comment]
> @yukgan
> wsnb！俺这种文盲一本都没看过

你妈嗨啊
